
@rootApi=http://localhost:8000



@userApi={{rootApi}}/api/v1/User-Agent: 

@bookingApi={{rootApi}}/api/v1/booking

### server testing
GET {{rootApi}}


# ========== user api =============
###get user 

GET {{userApi}}
Content-Type: application/json

{
    "fName":"Sam",
    "lName":"Smith",
    "phone":"01236544778",
    "address":"somewhere in the Sydney",
    "email":"sam@emaiul",
    "password":"123456"
}


###create user in db

POST {{userApi}}
Content-Type: application/json

{
    "role":"admin",
    "fName":"Sam",
    "lName":"Smith",
    "phone":"01236544778",
    "address":"somewhere in the Sydney",
    "email":"sam@emaiul.com",
    "password":"123456"
}



# ==================== Booking Api 
###=====create booking record
POST {{bookingApi}}
Content-Type: application/json

{
    "carId":"hagfsd4646",
    "carName":"BMW",
    "image":"http//:....",
    "userId":"sadfg4545",
    "userName":"sdfgdsg",
    "returnDate":"2024-1-22"
}